name: Docker Image Build

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - "**/docker-compose.yml.example"
      - "**/config.yml.example"
      - "**/.dockerignore"
      - "**/.gitignore"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.FAQ_DOCKERHUB_USERNAME }}
          password: ${{ secrets.FAQ_DOCKERHUB_TOKEN }}

      - name: Setup builder
        run: docker run --privileged --rm tonistiigi/binfmt --install all
      - run: docker buildx create --name builder --driver docker-container --platform linux/amd64,linux/arm64 --use
      - run: docker buildx inspect --bootstrap

      - name: Build image and push(py3.9)
        run: docker buildx build -t moefaq/v2board-telegram-bot:latest -t moefaq/v2board-telegram-bot:py3.9 --platform linux/amd64,linux/arm64 --progress plain --push -f dockerfiles/py3.9/Dockerfile .

      - name: Build image and push(py3.10)
        run: docker buildx build -t moefaq/v2board-telegram-bot:py3.10 --platform linux/amd64,linux/arm64 --progress plain --push -f dockerfiles/py3.10/Dockerfile .

      - name: Build image and push(py3.11)
        run: docker buildx build -t moefaq/v2board-telegram-bot:py3.11 --platform linux/amd64,linux/arm64 --progress plain --push -f dockerfiles/py3.11/Dockerfile .

      - name: Build image and push(py3.12)
        run: docker buildx build -t moefaq/v2board-telegram-bot:py3.12 --platform linux/amd64,linux/arm64 --progress plain --push -f dockerfiles/py3.12/Dockerfile .
